{ "-a", glkunix_arg_NumberValue, "Set the evaluation stack size" },
{ "-A", glkunix_arg_NumberValue, "Set the call stack size" },
{ "-c", glkunix_arg_NoValue, "Disable colors" },
{ "-C", glkunix_arg_NoValue, "Ignore the configuration file" },
{ "-d", glkunix_arg_NoValue, "Disable timed input" },
{ "-D", glkunix_arg_NoValue, "Disable sound effects" },
{ "-e", glkunix_arg_NoValue, "Enable ANSI escape sequences in the transcript" },
{ "-E", glkunix_arg_NoValue, "Set the escape string used to decorate transcripts (via -e)" },
{ "-f", glkunix_arg_NoValue, "Disable fixed-width fonts" },
{ "-F", glkunix_arg_NoValue, "Assume the default font is fixed-width" },
{ "-g", glkunix_arg_NoValue, "Disable the character graphics font" },
{ "-G", glkunix_arg_NoValue, "Select alternate box-drawing characters" },
{ "-h", glkunix_arg_NoValue, "Display this help message then exit" },
{ "-i", glkunix_arg_NoValue, "Print the ID of the specified game then exit" },
{ "-k", glkunix_arg_NoValue, "Disable terminating keys" },
{ "-m", glkunix_arg_NoValue, "Disable meta commands" },
{ "-n", glkunix_arg_NumberValue, "Set the interpreter number (see 11.1.3 in The Z-machine Standards Document 1.0)" },
{ "-N", glkunix_arg_ValueFollows, "Set the interpreter version to the single-character version (see 11.1.3.1 in The Z-machine Standards Document 1.0)" },
{ "-r", glkunix_arg_NoValue, "Play back a command record" },
{ "-R", glkunix_arg_ValueFollows, "Specify the filename for the command record replay" },
{ "-s", glkunix_arg_NoValue, "Turn on command recording" },
{ "-S", glkunix_arg_ValueFollows, "Specify the filename for the command record" },
{ "-t", glkunix_arg_NoValue, "Turn on transcripting" },
{ "-T", glkunix_arg_ValueFollows, "Specify the filename for the transcript" },
{ "-u", glkunix_arg_NumberValue, "Set the maximum number of UNDO slots" },
{ "-U", glkunix_arg_NoValue, "Disable UNDO compression" },
{ "-v", glkunix_arg_NoValue, "Display version and configuration information then exit" },
{ "-x", glkunix_arg_NoValue, "Disable abbreviations (x, g, z, o) provided by Bocfel for old Infocom games" },
{ "-X", glkunix_arg_NoValue, "Turn on Tandy censorship" },
{ "-y", glkunix_arg_NoValue, "Overwrite transcripts rather than appending to them" },
{ "-Y", glkunix_arg_NoValue, "Use internal UNDO handling code only" },
{ "-z", glkunix_arg_NumberValue, "Provide a seed for the PRNG" },
{ "-Z", glkunix_arg_ValueFollows, "Provide a file/device from which 32 bits will be read as a seed" },
