TERP=bocfel
DEFMACRO=-DZTERP_GLK -DGARGLK -DZTERP_UNIX
CFLAGS=-std=c99 $(INCL) $(DEFMACRO)
SRC=blorb.c branch.c dict.c glkstart.c iff.c io.c math.c memory.c meta.c objects.c osdep.c process.c \
		random.c screen.c sound.c stack.c unicode.c util.c zoom.c zterp.c
include ../terp.mk
