TERP=scare
CFLAGS=$(INCL)
SRC= sctafpar.c sctaffil.c scprops.c scvars.c scexpr.c scprintf.c \
     scinterf.c scparser.c sclibrar.c scrunner.c scevents.c scnpcs.c scobjcts.c \
     sctasks.c screstrs.c scgamest.c scserial.c scresour.c scutils.c scdebug.c \
     sclocale.c scmemos.c os_glk.c
include ../terp.mk
