TERP=alan2
DEFMACRO=-DGLK -DREVERSED
CFLAGS=-funsigned-char -Wno-parentheses $(INCL) $(DEFMACRO)
SRC=arun.c main.c debug.c args.c exe.c inter.c parse.c rules.c stack.c decode.c term.c reverse.c readline.c params.c \
    sysdep.c glkstart.c glkio.c alan.version.c
include ../terp.mk
