TERP=jacl
DEFMACRO=-DGLK -DGARGLK
CFLAGS=$(INCL) $(DEFMACRO)
SRC=jacl.c glk_startup.c findroute.c interpreter.c loader.c glk_saver.c logging.c parser.c display.c \
    utils.c jpp.c resolvers.c errors.c encapsulate.c libcsv.c
include ../terp.mk
