function(c_standard target version)
    set_property(TARGET ${target} PROPERTY C_STANDARD ${version})
    set_property(TARGET ${target} PROPERTY C_STANDARD_REQUIRED ON)
    set_property(TARGET ${target} PROPERTY C_EXTENSIONS OFF)
endfunction()

function(lto target)
    if(HAS_LTO)
        set_property(TARGET ${target} PROPERTY INTERPROCEDURAL_OPTIMIZATION TRUE)
    endif()
endfunction()

function(warnings target)
    if("${CMAKE_C_COMPILER_ID}" STREQUAL "GNU")
        target_compile_options(${target} PRIVATE -Wall -Wno-format-truncation)
    elseif("${CMAKE_C_COMPILER_ID}" STREQUAL "Clang")
        target_compile_options(${target} PRIVATE -Wall)
    endif()
endfunction()
