TERP=agility
DEFMACRO=-DGLK -DGLK_ANSI_ONLY
CFLAGS=$(INCL) $(DEFMACRO)
SRC=agtread.c gamedata.c util.c agxfile.c auxfile.c filename.c parser.c exec.c runverb.c metacommand.c savegame.c \
    debugcmd.c agil.c token.c disassemble.c object.c interface.c os_glk.o
include ../terp.mk
